config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/songs', to: 'songs#index'
  root "welcome#index"
  resources :users, only: [:new, :create, :show]
  resources :artists, shallow: true do
    resources :songs, except: [:index]
  end
  resources :songs, only: [:index]
  resources :playlists
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  namespace :admin do
    resources :categories, only: [:index]
  end
  resources :categories, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates_presence_of :name

  has_many :songs
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :playlist
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  validates_presence_of :title, :length, :play_count

  belongs_to :artist
  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :password_digest, :username
  validates_uniqueness_of :username
  has_secure_password

  enum role: %w(default admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  private

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
  
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    if Artist.create(artist_params)
      redirect_to artists_path
    else
      redirect_to new_artist_path
    end
  end

  def show
    @artist = Artist.find(params[:id])
    session[:secret] = "This time for real, though."
  end

  private

  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def destroy
    user = session[:user_id]
    reset_session
    redirect_to user_path(user)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def new
    @song = Song.new
    @artist = Artist.find(params[:artist_id])
  end

  def create
    @artist = Artist.find(params[:artist_id])
    song_data = song_params
    song_data[:artist_id] = @artist.id
    if Song.create(song_data)
      redirect_to songs_path
    else
      redirect_to new_artist_song_path(@artist)
    end
  end

  private

  def song_params
    params.require(:song).permit(:title, :length, :play_count, :artist_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h1>Admin Categories</h1>

app/views/artists/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <p> <%= link_to "Add New Artist", new_artist_path, id: "artist-link" %></p>

    <% @artists.each do |artist| %>
    <p><%= link_to artist.name, artist_path(artist) %></p>
    <% end %>
  </body>
</html>

app/views/artists/new.html.erb
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<%= @artist.name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicBox1804</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render partial: 'nav/login-bar' unless params[:controller] == 'sessions' && params[:action] == 'new'%>
    <%= render partial: 'nav/blank-nav' if params[:controller] == 'sessions' && params[:action] == 'new'%>
    <%= yield %>
  </body>
</html>

app/views/nav/_blank-nav.html.erb
<nav id="navigation">
</nav>

app/views/nav/_login-bar.html.erb
<nav id="navigation">
  <% if current_user %>
    <h1 id="welcome">Welcome, <%= current_user.username %>!</h1>
    <%= link_to "Log Out", logout_path, id: 'log-out', method: :delete %>
  <% else %>
    <%= link_to "Log In", login_path, id: 'log-in' %>
  <% end %>
</nav>

app/views/songs/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=Shrikhand" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Inconsolata|Shrikhand" rel="stylesheet">
    <title></title>
  </head>
  <body>
    <header class="head">
      <div>All Songs</div>
    </header>
    <section class="middle">
      <% @songs.each do |song| %>
      <article class="song-box">
        <img class="photo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/14-06-08_RiP_Slayer_Tom_Araya_2.JPG/220px-14-06-08_RiP_Slayer_Tom_Araya_2.JPG" alt="araya">
        <div class="space"><%= song.title %></div>
        <div class="space">Plays: <%= song.play_count %></div>
      </article>
      <% end %>
    </section>
  </body>
</html>

app/views/songs/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet">
  </head>
  <body class="whole-page">
    <%= form_for [@artist, @song], html: {id: 'new-song'} do |f| %>
      <h2 class="item-style">Create A New Song</h2>
        <%= f.label :title, class: 'item-style labels'%>
        <%= f.text_field :title, class: 'item-style text'%>
        <%= f.label :length, class: 'item-style labels'%>
        <%= f.text_field :length, class: 'item-style text' %>
        <%= f.label :play_count, class: 'item-style labels' %>
        <%= f.text_field :play_count, class: 'item-style text' %>
      <%= f.submit class: 'item-style button' %>
    <% end %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<%= f.label :username %>
<%= f.text_field :username %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.submit %>
<% end %>

app/views/welcome/index.html.erb
<%= link_to "Sign Up to Be a User", new_user_path %>
<%= link_to "I already have an account", login_path %>